# Generated by Django 5.0.1 on 2024-02-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_timetable', '0003_grade_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetable.teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetable.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetable.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetable.class'),
        ),
    ]
